INSERT INTO user (name, lastName, email, password, birthdate) VALUES ('Ricardo', 'Pacheco', 'ricardodpsx@gmail.com', '12345', '1987-09-26');
INSERT INTO user (name, lastName, email, password, birthdate) VALUES ('Jennifer', 'Cruz', 'jennifer.cruzz@gmail.com', '12345', '1987-06-21');
INSERT INTO user (name, lastName, email, password, birthdate) VALUES ('Anastasia', 'Pacheco', 'anathecat@cutecat.meow', '12345', '2014-09-19');
INSERT INTO wordpairset (uID, langFrom, langTo, name) VALUES (1, 'EN', 'SP', 'Talk nicely');
INSERT INTO wordpairset (uID, langFrom, langTo, name, level) VALUES (3, 'CAT', 'SP', 'Cat to human', 'Intermediate');
INSERT INTO wordpairset (uID, langFrom, langTo, name, description) VALUES (2, 'EN', 'SP', 'From Books', 'Vocabulary from books I read');
INSERT INTO wordpairset (uID, langFrom, langTo, name, description, level) VALUES (2, 'FR', 'EN', 'B1 Level 1', 'Vocabulary from french classes', 'Intermediate');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'ramshackle', 'Destartalado');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'pundits', 'Expertos');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Poignancy', 'Patetismo');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'bric-a-brac', 'Baratijas');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Bleak', 'Sombrío');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Bleak', 'Desolado');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'trenchant', 'Incisivo');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Confute', 'Refutar');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'hoopla', 'Alboroto');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'trifle', 'Minucia');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'trifle', 'tontería');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'befuddled', 'Perplejo');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'tethered', 'Atado');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'fiendishly', 'Diabólicamente');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'boilerplate', 'Repetitivo');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'caveat', 'Advertencia');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Foray', 'incursión');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Mawkish', 'empalagoso');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Punning', 'juegos de palabras');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Turf', 'Césped');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Lowbrow', 'de poca cultura');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Vaunt', 'Jactarse');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Sheepish', 'Vergonzoso');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'Rote', 'rutina');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('EN', 'SP', 'purvey', 'Proveer');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'programming', 'programmation');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'code', 'programmer');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'hiking', 'Promenade');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'Israel', 'Israël');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'arab', 'arabe');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('FR', 'EN', 'choose', 'choisir');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('CAT', 'SP', 'Meow', 'Hola');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('CAT', 'SP', 'Meeeeeeeow', 'Comida');
INSERT INTO wordpair (langFrom, langTo, wordFrom, wordTo) VALUES ('CAT', 'SP', 'Meoooooow', 'Atencion a mi');
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,1);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,2);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,3);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,4);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,5);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,6);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,7);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,8);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,9);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,10);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,11);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,12);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,13);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,14);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,15);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (1,16);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,17);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,18);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,19);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,20);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,21);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,22);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,23);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,24);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (3,25);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,26);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,27);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,28);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,29);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,30);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (4,31);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (2,32);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (2,33);
INSERT INTO set_word_relation (wpsID, wpID) VALUES (2,34)
INSERT INTO category (name) VALUES ('verb');
INSERT INTO category (name) VALUES ('nationality');
INSERT INTO category (name, description) VALUES ('feelings', 'ways in which I can feel');
INSERT INTO category (name, description) VALUES ('qualities', 'words to describe someone');
INSERT INTO category (name, description) VALUES ('needs', 'things I desire');
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 1, 8);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 3, 5);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 3, 6);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 3, 12);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 3, 13);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 4, 2);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 4, 3);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (1, 4, 7);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (3, 5, 33);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (3, 5, 34);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 1, 22);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 1, 25);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 1, 27);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 1, 31);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 2, 29);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 2, 30);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 3, 23);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 4, 18);
INSERT INTO user_category_word (uID, cID, wpID) VALUES (2, 4, 21);

INSERT INTO wordstats (wpID, uID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 1, 1, FALSE, NOW(), 1);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 2, 3, FALSE, NOW(), 3);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 3, 2, TRUE, NOW(), 0);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 4, 0, FALSE, NOW(), 0);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 5, 0, FALSE, NOW(), 0);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (1, 6, 4, TRUE, NOW(), 3);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (2, 17, 4, TRUE, NOW(), 3);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (2, 18, 4, TRUE, NOW(), 3);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (2, 19, 4, FALSE, NOW(), 4);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (2, 25, 4, FALSE, NOW(), 4);
INSERT INTO wordstats (uID, wpID, timesViewed, lastResult, lastViewed, timesWrong) VALUES (2, 26, 4, FALSE, NOW(), 2);
INSERT INTO wordstats (uID, wpID, timesViewed, lastViewed, timesWrong) VALUES (2, 27, 0, NOW(), 0);
INSERT INTO wordstats (uID, wpID, timesViewed, lastViewed, timesWrong) VALUES (3, 32, 0, NOW(), 0);
INSERT INTO wordstats (uID, wpID, timesViewed, lastViewed, timesWrong, lastResult) VALUES (3, 33, 4, NOW(), 4, FALSE);
INSERT INTO wordstats (uID, wpID, timesViewed, lastViewed, timesWrong, lastResult) VALUES (3, 34, 4, NOW(), 2, TRUE);
